package com.techouts.Assessment;

public class Hello_JVM {
    public static void main(String[] args) {
        //JVM IS A JAVA VIRTUAL MACHINE WHICH CONVERTS BYTE CODE INTO MACHINE CODE
        // IT MAKES JAVA PLATFORM INDEPENDENT MEANING SAME JAVA PROGRAM CAN RUN ON ANY PLATFORM
        //WRITE JAVA SOURCE CODE
        // COMPILE USING JAVAC, IT GENERATES (.CLASS FILE ) IN THE SAME PACKAGE THE SOURCE CODE THAT CONTAINED.
        // JVM EXECUTES .CLASS FILE WHICH IS BYTE CODE THEN CONVERTS IT INTO MACHINE UNDERSTANDABLE CODE.
        //[JAVA SOURCE CODE -> JAVAC COMPILER -> JVM -> MACHINE CODE]
        System.out.println("HELLO JVM");
    }
}
